title: Vibe Security Suite
logo: /docs/assets/logo.svg
theme: jekyll-theme-cayman
show_downloads: false

# Navigation links
nav:
  - title: "Home"
    url: "/"
  - title: "CLI"
    url: "/cli.html"
  - title: "GitHub Action"
    url: "/action.html"
  - title: "Docker"
    url: "/docker.html"
  - title: "Contributing"
    url: "/../CONTRIBUTING.md"
  - title: "Security"
    url: "/../SECURITY.md"
